import { Router } from "express";
import { authRequired } from "../middleware/auth.js";
import { guestAddItem, guestClear, guestCreate, guestGet, guestRemove, guestUpdateQty, userAddItem, userClear, userGet, userRemove, userUpdateQty } from "../controllers/cartController.js";
const router=Router();
router.post("/guest/create", guestCreate);
router.get("/guest/:cartId", guestGet);
router.post("/guest/:cartId/items", guestAddItem);
router.patch("/guest/:cartId/items/:itemId", guestUpdateQty);
router.delete("/guest/:cartId/items/:itemId", guestRemove);
router.post("/guest/:cartId/clear", guestClear);
router.get("/", authRequired, userGet);
router.post("/items", authRequired, userAddItem);
router.patch("/items/:itemId", authRequired, userUpdateQty);
router.delete("/items/:itemId", authRequired, userRemove);
router.post("/clear", authRequired, userClear);
export default router;
